### ISSUE TITLE
Guess What?

### ISSUE THREAD

**Issue by AitzazImtiaz** [JeffTheK/soli#1]
I am using Soli and it's good then ls. I tried it but let's beautify it! We use coloroma to color it!

**Comment by dima-k144** [comment]
I am happy that you liked it ;)

**Comment by AitzazImtiaz** [comment]
I am trying to redesign it to be extremely pretty

**Comment by AitzazImtiaz** [comment]
Also trying Data frame to redesign this to form an elegant way tomorrow.

**Comment by AitzazImtiaz** [comment]
Hey @JeffTheK I am designing soli to be convenient and smooth in showing data. I am going to run it and show on terminal but I am afraid maybe soli will lose some features.

**Comment by AitzazImtiaz** [comment]
Bro, I give up :(
It's way more hard to contribute to soli but still there is something important

**Comment by AitzazImtiaz** [comment]
🎉🎉🎉
